[[redirects]]
  from = "https://b-gorelkin.netlify.app"
  to = "https://b.gorelkin.me/"
  status = 301
  force = true
[[redirects]]
  from = "https://gorelkin.me"
  to = "https://b.gorelkin.me/"
  status = 301
  force = true
[[redirects]]
  from = "https://www.gorelkin.me"
  to = "https://b.gorelkin.me/"
  status = 301
  force = true
[[redirects]]
  from = "https://bgorelkin.netlify.app"
  to = "https://b.gorelkin.me/"
  status = 301
  force = true
